services:
  backend:
    container_name: innovationslabor_5safe_be
    image: giorginogreg/innovationlab-5safe-be:v1
    build:
      context: .
      dockerfile: Dockerfile_backend
      platforms:
        - "linux/amd64"
    #volumes:
    #  - /tmp/.X11-unix:/tmp/.X11-unix
    #  restart: always
    #network_mode: "host"
    #environment:
    #  DISPLAY: "host.docker.internal:0"
    ports:
      - 5000:5000
  frontend:
    container_name: innovationslabor_5safe_fe
    image: giorginogreg/innovationlab-5safe-fe:v11
    build:
      context: .
      dockerfile: Dockerfile_frontend
      platforms:
        - "linux/amd64"
    restart: always
    ports:
      - 8080:80
    #environment: