[tool.poetry]
name = "il-5safe"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "il_5safe"}]

[tool.poetry.dependencies]
python = "^3.10"
cython = "^0.29.34"
torch = "^2.0.0"
torchvision = "^0.15.1"
black = "^23.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
